curl https://hdrihaven.com/files/hdris/abandoned_slipway_2k.hdr --output abandoned_slipway_2k.hdr
curl https://hdrihaven.com/files/hdris/aft_lounge_2k.hdr --output aft_lounge_2k.hdr
curl https://hdrihaven.com/files/hdris/aristea_wreck_2k.hdr --output aristea_wreck_2k.hdr
curl https://hdrihaven.com/files/hdris/blouberg_sunrise_1_2k.hdr --output blouberg_sunrise_1_2k.hdr
curl https://hdrihaven.com/files/hdris/blouberg_sunrise_2_2k.hdr --output blouberg_sunrise_2_2k.hdr
curl https://hdrihaven.com/files/hdris/blue_lagoon_2k.hdr --output blue_lagoon_2k.hdr
curl https://hdrihaven.com/files/hdris/blue_lagoon_night_2k.hdr --output blue_lagoon_night_2k.hdr
curl https://hdrihaven.com/files/hdris/cannon_2k.exr --output cannon_2k.exr
curl https://hdrihaven.com/files/hdris/cape_hill_2k.hdr --output cape_hill_2k.hdr
curl https://hdrihaven.com/files/hdris/cloudy_cliffside_road_2k.hdr --output cloudy_cliffside_road_2k.hdr
curl https://hdrihaven.com/files/hdris/fish_hoek_beach_2k.hdr --output fish_hoek_beach_2k.hdr
curl https://hdrihaven.com/files/hdris/furry_clouds_2k.hdr --output furry_clouds_2k.hdr
curl https://hdrihaven.com/files/hdris/pink_sunrise_2k.hdr --output pink_sunrise_2k.hdr
curl https://hdrihaven.com/files/hdris/red_hill_curve_2k.hdr --output red_hill_curve_2k.hdr
curl https://hdrihaven.com/files/hdris/red_hill_straight_2k.hdr --output red_hill_straight_2k.hdr
curl https://hdrihaven.com/files/hdris/secluded_beach_2k.hdr --output secluded_beach_2k.hdr
curl https://hdrihaven.com/files/hdris/simons_town_harbour_2k.hdr --output simons_town_harbour_2k.hdr
curl https://hdrihaven.com/files/hdris/simons_town_rocks_2k.hdr --output simons_town_rocks_2k.hdr
curl https://hdrihaven.com/files/hdris/the_sky_is_on_fire_2k.hdr --output the_sky_is_on_fire_2k.hdr
curl https://hdrihaven.com/files/hdris/tucker_wreck_2k.hdr --output tucker_wreck_2k.hdr
curl https://hdrihaven.com/files/hdris/umhlanga_sunrise_2k.hdr --output umhlanga_sunrise_2k.hdr
curl https://hdrihaven.com/files/hdris/venice_sunset_2k.hdr --output venice_sunset_2k.hdr
curl https://hdrihaven.com/files/hdris/vignaioli_2k.hdr --output vignaioli_2k.hdr
curl https://hdrihaven.com/files/hdris/white_cliff_top_2k.hdr --output white_cliff_top_2k.hdr
